[versions]
agp = "8.13.1"
biometric = "1.1.0"
composeMarkdown = "0.5.7"
kotlin = "2.0.21"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockwebserver = "4.12.0"
securityCrypto = "1.1.0"
testRules = "1.7.0"
activityCompose = "1.12.0"
lottieCompose = "6.7.1"
navigationCompose = "2.9.6"
iconsCompose = "1.7.8"
composeBom = "2025.11.01"
androidxHilt = "1.3.0"
adaptiveAndroid = "1.2.0"
hilt = "2.57.2"
ksp = "2.0.21-1.0.28"

datastorePreferences = "1.2.0"
googlePlayServices = "4.4.4"
crashlytics = "3.0.6"

oneSignal = "5.4.1"
ossLicenses = "0.10.9"
retrofit = "3.0.0"

firebaseBom = "34.6.0"

realm = "3.0.0"

mockk = "1.14.6"
coroutineTest = "1.10.2"
firebaseAppDistribution = "5.2.0"
kover = "0.9.3"
sonarqube = "7.1.0.6387"
playServicesMeasurementApi = "23.0.0"
playServicesOssLicenses = "17.3.0"
googleAccompanist = "0.37.3"
browser = "1.9.0"
googleTagManager = "18.3.0"

openid = "0.11.1"

gov-secure-store = "0.12.1"
tink = "1.20.0"

[libraries]
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "iconsCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
androidx-adaptive-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "adaptiveAndroid" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-appcheck-play = { group = "com.google.firebase", name = "firebase-appcheck-playintegrity" }

mockk = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutineTest" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
one-signal = { module = "com.onesignal:OneSignal", version.ref = "oneSignal" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
realm-base = { group = "io.realm.kotlin", name = "library-base", version.ref = "realm"}
play-services-measurement-api = { group = "com.google.android.gms", name = "play-services-measurement-api", version.ref = "playServicesMeasurementApi" }
play-services-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
oss-licenses = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "ossLicenses" }
google-tag-manager = { group = "com.google.android.gms", name = "play-services-tagmanager", version.ref = "googleTagManager" }

openid = { group = "net.openid", name = "appauth", version.ref = "openid"}

gov-securestore = { group = "uk.gov.securestore", name = "app", version.ref = "gov-secure-store"}

# A library that provides Android runtime permissions support for Jetpack Compose
google-accompanist = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "googleAccompanist" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
google-crypto-tink = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-play-services = { id = "com.google.gms.google-services", version.ref = "googlePlayServices" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebaseAppDistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
